# Generated by Django 5.2.8 on 2025-12-05 04:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('instagram_signal', models.FloatField(default=0.0)),
                ('local_usage_signal', models.FloatField(default=0.0)),
                ('trends_signal', models.FloatField(default=0.0)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popularity', to='places.place')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
